services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER:-postgres}
    container_name: tasks-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
